# Generated by Django 5.2.7 on 2025-10-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the menu item', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Enter the description of the menu item')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in £', max_digits=10)),
                ('category', models.CharField(choices=[('appetizer', 'Appetizer'), ('main', 'Main Course'), ('dessert', 'Dessert'), ('drink', 'Drink')], default='main', help_text='Select the category of the menu item', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Upload an image of the menu item', null=True, upload_to='menu_images/')),
                ('is_available', models.BooleanField(default=True, help_text='Is the menu item available?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time the menu item was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date and time the menu item was last updated')),
            ],
            options={
                'verbose_name': ('Menu Item',),
                'verbose_name_plural': 'Menu Items',
                'ordering': (['category', 'name'],),
            },
        ),
    ]
